import { House, Address } from '../interfaces/house';

export const SAMPLE_HOUSES: House[] = [
  {
    id: '1',
    title: 'Modern Family Home',
    description: 'A beautiful modern family home with spacious garden and pool.',
    price: 450000,
    address: {
      street: '12 Independence Ave',
      city: 'Accra',
      state: 'Greater Accra',
      zipCode: 'GA-123-4567',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1501183638710-841dd1904471?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
      'https://images.unsplash.com/photo-1460518451285-97b6aa326961',
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    listedBy: 'agent-1',
    available: true,
    features: ['Pool', 'Garage', 'Garden'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '2',
    title: 'Downtown Apartment',
    description: 'Cozy apartment in the heart of the city, close to all amenities.',
    price: 320000,
    address: {
      street: '5 Oxford Street',
      city: 'Osu',
      state: 'Greater Accra',
      zipCode: 'GA-456-7890',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
    ],
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    listedBy: 'agent-2',
    available: true,
    features: ['Balcony', 'Elevator'],
    listingType: 'rent',
    propertyType: 'apartment',
  },
  {
    id: '3',
    title: 'Luxury Beachfront Villa',
    description: 'Stunning villa with ocean views, private beach access, and modern amenities.',
    price: 1200000,
    address: {
      street: '1 Labadi Beach Road',
      city: 'Labadi',
      state: 'Greater Accra',
      zipCode: 'GA-789-1234',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
    ],
    bedrooms: 5,
    bathrooms: 5,
    area: 5000,
    listedBy: 'agent-1',
    available: false,
    features: ['Beachfront', 'Infinity Pool', 'Home Theater', 'Smart Home'],
    listingType: 'sale',
    propertyType: 'villa',
  },
  {
    id: '4',
    title: 'Suburban Starter Home',
    description: 'Affordable single-family home in a quiet neighborhood, perfect for first-time buyers.',
    price: 210000,
    address: {
      street: '23 Spintex Road',
      city: 'Tema',
      state: 'Greater Accra',
      zipCode: 'GE-234-5678',
      country: 'Ghana',
    },
    images: [
      'https://static.wixstatic.com/media/6800cb_9bf2a114a40249fc8a8364ae60993b0a~mv2.jpg/v1/fill/w_1024,h_576,al_c,q_85,enc_avif,quality_auto/6800cb_9bf2a114a40249fc8a8364ae60993b0a~mv2.jpg',
      'https://static.wixstatic.com/media/6800cb_350ac90c4d454ff191c2d97af0a64ca2~mv2.jpg/v1/fill/w_1024,h_576,al_c,q_85,enc_avif,quality_auto/6800cb_350ac90c4d454ff191c2d97af0a64ca2~mv2.jpg',
      'https://static.wixstatic.com/media/6800cb_95e9451ff60a49938d7c182c39b2f236~mv2.jpg/v1/fill/w_1024,h_576,al_c,q_85,enc_avif,quality_auto/6800cb_95e9451ff60a49938d7c182c39b2f236~mv2.jpg',
      'https://static.wixstatic.com/media/6800cb_e74dfbe82615441ebd4e67eb54c06d70~mv2.jpg/v1/fill/w_768,h_432,al_c,q_80,enc_avif,quality_auto/6800cb_e74dfbe82615441ebd4e67eb54c06d70~mv2.jpg',
      'https://static.wixstatic.com/media/6800cb_4ef567f44d1d4c42b068d76114a0ee01~mv2.jpg/v1/fill/w_1024,h_576,al_c,q_85,enc_avif,quality_auto/6800cb_4ef567f44d1d4c42b068d76114a0ee01~mv2.jpg',
      'https://static.wixstatic.com/media/6800cb_2a8d9659d05949b7837b6b37b7b4fcf7~mv2.jpg/v1/fill/w_1024,h_576,al_c,q_85,enc_avif,quality_auto/6800cb_2a8d9659d05949b7837b6b37b7b4fcf7~mv2.jpg'
    ],
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    listedBy: 'agent-2',
    available: true,
    features: ['Garage', 'Basement', 'Fenced Yard'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '5',
    title: 'Urban Loft',
    description: 'Trendy loft apartment with open floor plan and city skyline views.',
    price: 540000,
    address: {
      street: '15 Liberation Road',
      city: 'Accra',
      state: 'Greater Accra',
      zipCode: 'GA-321-6549',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1464983953574-0892a716854b',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 900,
    listedBy: 'agent-1',
    available: true,
    features: ['Open Floor Plan', 'Rooftop Access', 'Pet Friendly'],
    listingType: 'rent',
    propertyType: 'loft',
  },
  {
    id: '6',
    title: 'Mountain Cabin Retreat',
    description: 'Rustic cabin with breathtaking mountain views and hiking trails nearby.',
    price: 375000,
    address: {
      street: '7 Aburi Hills',
      city: 'Aburi',
      state: 'Eastern Region',
      zipCode: 'ER-111-2222',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
    ],
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    listedBy: 'agent-2',
    available: true,
    features: ['Fireplace', 'Deck', 'Mountain View'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '7',
    title: 'Historic Townhouse',
    description: 'Charming townhouse in a historic district, recently renovated.',
    price: 600000,
    address: {
      street: '10 Cape Coast Castle Road',
      city: 'Cape Coast',
      state: 'Central Region',
      zipCode: 'CR-333-4444',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1464983953574-0892a716854b',
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    listedBy: 'agent-1',
    available: true,
    features: ['Historic', 'Courtyard', 'Renovated'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '8',
    title: 'Country Farmhouse',
    description: 'Spacious farmhouse with barn and acres of land, ideal for horses.',
    price: 480000,
    address: {
      street: '3 Kumasi Road',
      city: 'Kumasi',
      state: 'Ashanti Region',
      zipCode: 'AS-555-6666',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    ],
    bedrooms: 5,
    bathrooms: 4,
    area: 3500,
    listedBy: 'agent-2',
    available: true,
    features: ['Barn', 'Acreage', 'Wraparound Porch'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '9',
    title: 'Lakefront Cottage',
    description: 'Cozy cottage with private dock and beautiful lake views.',
    price: 390000,
    address: {
      street: '22 Volta Lake Road',
      city: 'Akosombo',
      state: 'Eastern Region',
      zipCode: 'ER-777-8888',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
    ],
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    listedBy: 'agent-1',
    available: false,
    features: ['Lakefront', 'Dock', 'Firepit'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '10',
    title: 'Eco-Friendly Smart Home',
    description: 'Modern home with solar panels, smart appliances, and energy-efficient design.',
    price: 700000,
    address: {
      street: '8 Ridge Road',
      city: 'Accra',
      state: 'Greater Accra',
      zipCode: 'GA-654-9870',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca',
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 2600,
    listedBy: 'agent-2',
    available: true,
    features: ['Solar Panels', 'Smart Home', 'EV Charger'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '11',
    title: 'Desert Oasis',
    description: 'Beautiful home with pool and desert landscaping, perfect for warm climates.',
    price: 520000,
    address: {
      street: '4 Tamale Road',
      city: 'Tamale',
      state: 'Northern Region',
      zipCode: 'NR-111-3333',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1523217582562-09d0def993a6',
    ],
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    listedBy: 'agent-1',
    available: true,
    features: ['Pool', 'Desert Landscaping', 'Patio'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '12',
    title: 'Penthouse Suite',
    description: 'Luxury penthouse with panoramic city views and private elevator access.',
    price: 1500000,
    address: {
      street: '2 Airport City',
      city: 'Accra',
      state: 'Greater Accra',
      zipCode: 'GA-888-9999',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
    ],
    bedrooms: 3,
    bathrooms: 4,
    area: 3200,
    listedBy: 'agent-2',
    available: false,
    features: ['Penthouse', 'Private Elevator', 'City View'],
    listingType: 'sale',
    propertyType: 'apartment',
  },
  {
    id: '13',
    title: 'Tiny Home',
    description: 'Efficient and affordable tiny home, perfect for minimalist living.',
    price: 95000,
    address: {
      street: '9 Adenta Road',
      city: 'Adenta',
      state: 'Greater Accra',
      zipCode: 'GA-222-3333',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
    ],
    bedrooms: 1,
    bathrooms: 1,
    area: 400,
    listedBy: 'agent-1',
    available: true,
    features: ['Tiny Home', 'Minimalist', 'Efficient'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '14',
    title: 'Classic Colonial',
    description: 'Traditional colonial home with spacious yard and classic architecture.',
    price: 430000,
    address: {
      street: '17 Sekondi Road',
      city: 'Sekondi',
      state: 'Western Region',
      zipCode: 'WR-444-5555',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1460518451285-97b6aa326961',
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 2700,
    listedBy: 'agent-2',
    available: true,
    features: ['Colonial', 'Large Yard', 'Fireplace'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '15',
    title: 'Modern Row House',
    description: 'Contemporary row house in a vibrant urban neighborhood.',
    price: 380000,
    address: {
      street: '6 Kanda Highway',
      city: 'Accra',
      state: 'Greater Accra',
      zipCode: 'GA-555-6666',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1464983953574-0892a716854b',
    ],
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    listedBy: 'agent-1',
    available: true,
    features: ['Row House', 'Modern', 'Walkable'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '16',
    title: 'Ski Chalet',
    description: 'Cozy chalet near ski slopes, perfect for winter getaways.',
    price: 650000,
    address: {
      street: '1 Kwahu Ridge',
      city: 'Kwahu',
      state: 'Eastern Region',
      zipCode: 'ER-999-0000',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1501594907352-04cda38ebc29',
    ],
    bedrooms: 4,
    bathrooms: 3,
    area: 2300,
    listedBy: 'agent-2',
    available: true,
    features: ['Mountain View', 'Fireplace', 'Hot Tub'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '17',
    title: 'Victorian Mansion',
    description: 'Grand Victorian mansion with ornate details and large garden.',
    price: 2000000,
    address: {
      street: '3 Ridge Road',
      city: 'Kumasi',
      state: 'Ashanti Region',
      zipCode: 'AS-777-8888',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1460518451285-97b6aa326961',
    ],
    bedrooms: 6,
    bathrooms: 5,
    area: 7000,
    listedBy: 'agent-1',
    available: false,
    features: ['Victorian', 'Garden', 'Historic'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '18',
    title: 'Golf Course Estate',
    description: 'Elegant estate home overlooking a championship golf course.',
    price: 1100000,
    address: {
      street: '2 Achimota Golf Road',
      city: 'Accra',
      state: 'Greater Accra',
      zipCode: 'GA-888-1111',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb',
    ],
    bedrooms: 5,
    bathrooms: 4,
    area: 4800,
    listedBy: 'agent-2',
    available: true,
    features: ['Golf Course', 'Pool', 'Gated Community'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '19',
    title: 'Seaside Bungalow',
    description: 'Charming bungalow steps from the beach, perfect for summer vacations.',
    price: 420000,
    address: {
      street: '8 Busua Beach Road',
      city: 'Busua',
      state: 'Western Region',
      zipCode: 'WR-222-3333',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
    ],
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    listedBy: 'agent-1',
    available: true,
    features: ['Beach Access', 'Porch', 'Bungalow'],
    listingType: 'sale',
    propertyType: 'house',
  },
  {
    id: '20',
    title: 'Downtown Studio',
    description: 'Compact studio apartment in the heart of downtown, ideal for young professionals.',
    price: 275000,
    address: {
      street: '14 Ring Road Central',
      city: 'Accra',
      state: 'Greater Accra',
      zipCode: 'GA-444-5555',
      country: 'Ghana',
    },
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd',
    ],
    bedrooms: 0,
    bathrooms: 1,
    area: 500,
    listedBy: 'agent-2',
    available: true,
    features: ['Studio', 'Downtown', 'Modern'],
    listingType: 'rent',
    propertyType: 'apartment',
  },
]; 